# Cloudflare Pages configuration for ADHD Hub
name = "adhd-hub"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "adhd-hub.pages.dev/*", zone_name = "pages.dev" }
]

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Asset optimization
[build.upload]
format = "modules"

# Custom headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback for client-side routing (if needed)
[[redirects]]
from = "/404.html"
to = "/404"
status = 404